#include <stdexcept>

int main (int argc, char *argv[]) {
    throw std::exception();
}
